// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // obj_tile_1
global.__objectDepths[1] = 0; // obj_tile_2
global.__objectDepths[2] = 0; // obj_tile_3
global.__objectDepths[3] = 0; // obj_tile_4
global.__objectDepths[4] = 0; // obj_tile_5
global.__objectDepths[5] = 0; // obj_tile_6
global.__objectDepths[6] = 0; // obj_tile_7
global.__objectDepths[7] = 0; // obj_tile_8
global.__objectDepths[8] = 0; // obj_tile_9
global.__objectDepths[9] = 0; // obj_tile_10
global.__objectDepths[10] = 0; // obj_tile_11
global.__objectDepths[11] = 0; // obj_tile_12
global.__objectDepths[12] = 0; // obj_tile_13
global.__objectDepths[13] = 0; // obj_tile_14
global.__objectDepths[14] = 0; // obj_tile_15
global.__objectDepths[15] = 0; // obj_tile_16
global.__objectDepths[16] = 0; // obj_tile_17
global.__objectDepths[17] = 0; // obj_tile_18
global.__objectDepths[18] = 0; // obj_tile_19
global.__objectDepths[19] = 0; // obj_tile_20
global.__objectDepths[20] = 0; // obj_tile_21
global.__objectDepths[21] = 0; // obj_tile_22
global.__objectDepths[22] = 0; // obj_tile_23
global.__objectDepths[23] = 0; // obj_tile_24
global.__objectDepths[24] = 0; // obj_tile_25
global.__objectDepths[25] = 0; // obj_tile_26
global.__objectDepths[26] = 0; // obj_tile_27
global.__objectDepths[27] = 0; // obj_tile_28
global.__objectDepths[28] = 0; // obj_tile_29
global.__objectDepths[29] = 0; // obj_tile_30
global.__objectDepths[30] = 0; // obj_tile_31
global.__objectDepths[31] = 0; // obj_tile_32
global.__objectDepths[32] = 0; // obj_tile_33
global.__objectDepths[33] = 0; // obj_tile_34
global.__objectDepths[34] = 0; // obj_tile_35
global.__objectDepths[35] = 0; // obj_tile_36
global.__objectDepths[36] = 0; // obj_tile_37
global.__objectDepths[37] = 0; // obj_tile_38
global.__objectDepths[38] = 0; // obj_tile_39
global.__objectDepths[39] = 0; // obj_tile_40
global.__objectDepths[40] = 0; // obj_tile_41
global.__objectDepths[41] = 0; // obj_tile_42
global.__objectDepths[42] = 0; // obj_tile_43
global.__objectDepths[43] = 0; // obj_tile_44
global.__objectDepths[44] = 0; // obj_tile_45
global.__objectDepths[45] = 0; // obj_tile_46
global.__objectDepths[46] = 0; // obj_tile_47
global.__objectDepths[47] = 0; // obj_tile_48
global.__objectDepths[48] = 0; // obj_tile_49
global.__objectDepths[49] = 0; // obj_tile_50
global.__objectDepths[50] = 0; // obj_tile_51
global.__objectDepths[51] = 0; // obj_tile_52
global.__objectDepths[52] = 0; // obj_tile_53
global.__objectDepths[53] = 0; // object176
global.__objectDepths[54] = 0; // object177
global.__objectDepths[55] = 0; // object179
global.__objectDepths[56] = 0; // object178
global.__objectDepths[57] = 0; // object180
global.__objectDepths[58] = 0; // object181
global.__objectDepths[59] = 0; // object182
global.__objectDepths[60] = 0; // object183
global.__objectDepths[61] = 0; // object184
global.__objectDepths[62] = 0; // object185
global.__objectDepths[63] = 0; // object186
global.__objectDepths[64] = 0; // object187
global.__objectDepths[65] = 0; // object188
global.__objectDepths[66] = 0; // object189
global.__objectDepths[67] = 0; // object190
global.__objectDepths[68] = 0; // object195
global.__objectDepths[69] = 0; // object193
global.__objectDepths[70] = 0; // object198
global.__objectDepths[71] = 0; // object199
global.__objectDepths[72] = 0; // object200
global.__objectDepths[73] = 0; // object201
global.__objectDepths[74] = 0; // object202
global.__objectDepths[75] = 0; // object209
global.__objectDepths[76] = 0; // object239
global.__objectDepths[77] = 0; // object240
global.__objectDepths[78] = 0; // object204
global.__objectDepths[79] = 0; // object207
global.__objectDepths[80] = 0; // object205
global.__objectDepths[81] = 0; // object208
global.__objectDepths[82] = 0; // object206
global.__objectDepths[83] = 0; // object203
global.__objectDepths[84] = 0; // object265
global.__objectDepths[85] = 0; // object191
global.__objectDepths[86] = 0; // object192
global.__objectDepths[87] = 0; // object194
global.__objectDepths[88] = 0; // object196
global.__objectDepths[89] = 0; // object197
global.__objectDepths[90] = 0; // object210
global.__objectDepths[91] = 0; // object211
global.__objectDepths[92] = 0; // object212
global.__objectDepths[93] = 0; // object213
global.__objectDepths[94] = 0; // object214
global.__objectDepths[95] = 0; // object215
global.__objectDepths[96] = 0; // object216
global.__objectDepths[97] = 0; // object217
global.__objectDepths[98] = 0; // object218
global.__objectDepths[99] = 0; // object219
global.__objectDepths[100] = 0; // object220
global.__objectDepths[101] = 0; // object221
global.__objectDepths[102] = 0; // object222
global.__objectDepths[103] = 0; // object223
global.__objectDepths[104] = 0; // object224
global.__objectDepths[105] = 0; // object225
global.__objectDepths[106] = 0; // object226
global.__objectDepths[107] = 0; // object227
global.__objectDepths[108] = 0; // object228
global.__objectDepths[109] = 0; // object229
global.__objectDepths[110] = 0; // object230
global.__objectDepths[111] = 0; // object231
global.__objectDepths[112] = 0; // object232
global.__objectDepths[113] = 0; // object233
global.__objectDepths[114] = 0; // object234
global.__objectDepths[115] = 0; // object235
global.__objectDepths[116] = 0; // object236
global.__objectDepths[117] = 0; // object237
global.__objectDepths[118] = 0; // object238
global.__objectDepths[119] = 0; // object241
global.__objectDepths[120] = 0; // object242
global.__objectDepths[121] = 0; // object243
global.__objectDepths[122] = 0; // object244
global.__objectDepths[123] = 0; // object245
global.__objectDepths[124] = 0; // object246
global.__objectDepths[125] = 0; // object247
global.__objectDepths[126] = 0; // object248
global.__objectDepths[127] = 0; // object249
global.__objectDepths[128] = 0; // object250
global.__objectDepths[129] = 0; // object251
global.__objectDepths[130] = 0; // object252
global.__objectDepths[131] = 0; // object256
global.__objectDepths[132] = 0; // object257
global.__objectDepths[133] = 0; // object258
global.__objectDepths[134] = 0; // object259
global.__objectDepths[135] = 0; // object260
global.__objectDepths[136] = 0; // object261
global.__objectDepths[137] = 0; // object262
global.__objectDepths[138] = 0; // object263
global.__objectDepths[139] = 0; // object264
global.__objectDepths[140] = 10; // object273
global.__objectDepths[141] = 10; // object266
global.__objectDepths[142] = 10; // object274
global.__objectDepths[143] = 2; // object253
global.__objectDepths[144] = 2; // object254
global.__objectDepths[145] = 2; // object255
global.__objectDepths[146] = 1; // obj_player
global.__objectDepths[147] = 0; // obj_flag
global.__objectDepths[148] = 10; // obj_ladder
global.__objectDepths[149] = 0; // obj_gun
global.__objectDepths[150] = 0; // obj_jetpack
global.__objectDepths[151] = 0; // obj_no_entry
global.__objectDepths[152] = 2; // obj_room_next
global.__objectDepths[153] = 0; // obj_block2
global.__objectDepths[154] = 0; // obj_block3
global.__objectDepths[155] = 10; // obj_win_plat
global.__objectDepths[156] = 0; // obj_platform_h
global.__objectDepths[157] = 0; // obj_platform_v
global.__objectDepths[158] = 0; // obj_crumble_block
global.__objectDepths[159] = 0; // obj_gemblock
global.__objectDepths[160] = 0; // obj_breakable
global.__objectDepths[161] = 0; // obj_solid
global.__objectDepths[162] = 0; // obj_springblock
global.__objectDepths[163] = -2; // obj_spike_d
global.__objectDepths[164] = 0; // obj_spike_r
global.__objectDepths[165] = 0; // obj_spike
global.__objectDepths[166] = 0; // obj_spike_l
global.__objectDepths[167] = 0; // obj_water
global.__objectDepths[168] = -2; // obj_example_enemy
global.__objectDepths[169] = -2; // obj_spike_u
global.__objectDepths[170] = 2; // obj_stationary
global.__objectDepths[171] = 2; // obj_walker
global.__objectDepths[172] = 2; // obj_riser
global.__objectDepths[173] = 2; // obj_ducker
global.__objectDepths[174] = 2; // obj_faller
global.__objectDepths[175] = 2; // obj_jumper
global.__objectDepths[176] = 2; // obj_floater
global.__objectDepths[177] = 2; // obj_sticky
global.__objectDepths[178] = 2; // obj_waver
global.__objectDepths[179] = 2; // obj_swinger
global.__objectDepths[180] = 2; // obj_follower
global.__objectDepths[181] = 2; // obj_liner
global.__objectDepths[182] = 2; // obj_ponger
global.__objectDepths[183] = 2; // obj_geobound
global.__objectDepths[184] = 2; // obj_tethered
global.__objectDepths[185] = 2; // obj_swooper
global.__objectDepths[186] = 0; // par_enemy
global.__objectDepths[187] = 0; // par_platform
global.__objectDepths[188] = 0; // par_event
global.__objectDepths[189] = 0; // par_solid
global.__objectDepths[190] = 0; // par_ladder
global.__objectDepths[191] = 0; // par_liquid
global.__objectDepths[192] = 0; // obj_commands
global.__objectDepths[193] = 0; // obj_gen
global.__objectDepths[194] = 0; // obj_data
global.__objectDepths[195] = -100; // obj_gui
global.__objectDepths[196] = 0; // obj_music
global.__objectDepths[197] = 0; // obj_view
global.__objectDepths[198] = 0; // obj_instance_control
global.__objectDepths[199] = 0; // obj_camera
global.__objectDepths[200] = -5; // obj_room
global.__objectDepths[201] = 0; // obj_game_over
global.__objectDepths[202] = 0; // obj_disappear
global.__objectDepths[203] = 0; // obj_go_to_boss
global.__objectDepths[204] = 0; // obj_trans_waterfall1
global.__objectDepths[205] = 0; // obj_trans_waterfall2
global.__objectDepths[206] = -100; // obj_transition_open
global.__objectDepths[207] = -100; // obj_transition_close
global.__objectDepths[208] = 5; // obj_waterfall
global.__objectDepths[209] = 0; // obj_levelportal
global.__objectDepths[210] = 0; // obj_levelportal_2
global.__objectDepths[211] = 0; // obj_pedestal
global.__objectDepths[212] = 0; // obj_item
global.__objectDepths[213] = 20; // obj_title
global.__objectDepths[214] = -5; // obj_particle_jump
global.__objectDepths[215] = -5; // obj_particle_land
global.__objectDepths[216] = 0; // obj_drillsparks
global.__objectDepths[217] = 0; // obj_enemy_shot
global.__objectDepths[218] = 0; // obj_cannonball
global.__objectDepths[219] = 0; // obj_run_timer
global.__objectDepths[220] = 0; // obj_win_timer
global.__objectDepths[221] = -2; // obj_blacksolid
global.__objectDepths[222] = 0; // obj_invisblock
global.__objectDepths[223] = 3; // obj_water2
global.__objectDepths[224] = 0; // obj_chunk
global.__objectDepths[225] = 0; // obj_chunk_breakable
global.__objectDepths[226] = 0; // obj_chunk_solid
global.__objectDepths[227] = 0; // obj_chunk_surface
global.__objectDepths[228] = 0; // obj_block_spawner
global.__objectDepths[229] = 6; // obj_blood_splat
global.__objectDepths[230] = -20; // obj_burst_particle
global.__objectDepths[231] = -10; // obj_explosion
global.__objectDepths[232] = -10; // obj_explosion_2
global.__objectDepths[233] = -10; // obj_explosion_silent
global.__objectDepths[234] = 0; // obj_ore
global.__objectDepths[235] = 0; // obj_next_room
global.__objectDepths[236] = 0; // obj_piece
global.__objectDepths[237] = 0; // obj_platform
global.__objectDepths[238] = 0; // obj_platform_backup
global.__objectDepths[239] = -10; // obj_shot
global.__objectDepths[240] = -10; // obj_shot_splash
global.__objectDepths[241] = -10; // obj_shot_splash_invul
global.__objectDepths[242] = -15; // obj_shot_splash_dir
global.__objectDepths[243] = 10; // obj_train
global.__objectDepths[244] = 6; // obj_train_door
global.__objectDepths[245] = 10; // obj_train_platform
global.__objectDepths[246] = 5; // obj_switch_call
global.__objectDepths[247] = 5; // obj_switch_dismiss
global.__objectDepths[248] = 10; // obj_train_interior
global.__objectDepths[249] = 0; // obj_train_floor
global.__objectDepths[250] = 0; // obj_train_ceiling
global.__objectDepths[251] = 0; // obj_conductor
global.__objectDepths[252] = -5; // obj_speech
global.__objectDepths[253] = 5; // obj_furnace
global.__objectDepths[254] = 0; // obj_create_player
global.__objectDepths[255] = 0; // obj_lilboy
global.__objectDepths[256] = 0; // obj_boss_plat
global.__objectDepths[257] = 0; // obj_crawler
global.__objectDepths[258] = 0; // obj_pipe
global.__objectDepths[259] = 0; // spr_blobboy
global.__objectDepths[260] = 0; // obj_longboy
global.__objectDepths[261] = 0; // obj_lickboy
global.__objectDepths[262] = 0; // obj_boulder
global.__objectDepths[263] = -2; // obj_enemy
global.__objectDepths[264] = 0; // obj_floaty
global.__objectDepths[265] = 2; // obj_boss


global.__objectNames[0] = "obj_tile_1";
global.__objectNames[1] = "obj_tile_2";
global.__objectNames[2] = "obj_tile_3";
global.__objectNames[3] = "obj_tile_4";
global.__objectNames[4] = "obj_tile_5";
global.__objectNames[5] = "obj_tile_6";
global.__objectNames[6] = "obj_tile_7";
global.__objectNames[7] = "obj_tile_8";
global.__objectNames[8] = "obj_tile_9";
global.__objectNames[9] = "obj_tile_10";
global.__objectNames[10] = "obj_tile_11";
global.__objectNames[11] = "obj_tile_12";
global.__objectNames[12] = "obj_tile_13";
global.__objectNames[13] = "obj_tile_14";
global.__objectNames[14] = "obj_tile_15";
global.__objectNames[15] = "obj_tile_16";
global.__objectNames[16] = "obj_tile_17";
global.__objectNames[17] = "obj_tile_18";
global.__objectNames[18] = "obj_tile_19";
global.__objectNames[19] = "obj_tile_20";
global.__objectNames[20] = "obj_tile_21";
global.__objectNames[21] = "obj_tile_22";
global.__objectNames[22] = "obj_tile_23";
global.__objectNames[23] = "obj_tile_24";
global.__objectNames[24] = "obj_tile_25";
global.__objectNames[25] = "obj_tile_26";
global.__objectNames[26] = "obj_tile_27";
global.__objectNames[27] = "obj_tile_28";
global.__objectNames[28] = "obj_tile_29";
global.__objectNames[29] = "obj_tile_30";
global.__objectNames[30] = "obj_tile_31";
global.__objectNames[31] = "obj_tile_32";
global.__objectNames[32] = "obj_tile_33";
global.__objectNames[33] = "obj_tile_34";
global.__objectNames[34] = "obj_tile_35";
global.__objectNames[35] = "obj_tile_36";
global.__objectNames[36] = "obj_tile_37";
global.__objectNames[37] = "obj_tile_38";
global.__objectNames[38] = "obj_tile_39";
global.__objectNames[39] = "obj_tile_40";
global.__objectNames[40] = "obj_tile_41";
global.__objectNames[41] = "obj_tile_42";
global.__objectNames[42] = "obj_tile_43";
global.__objectNames[43] = "obj_tile_44";
global.__objectNames[44] = "obj_tile_45";
global.__objectNames[45] = "obj_tile_46";
global.__objectNames[46] = "obj_tile_47";
global.__objectNames[47] = "obj_tile_48";
global.__objectNames[48] = "obj_tile_49";
global.__objectNames[49] = "obj_tile_50";
global.__objectNames[50] = "obj_tile_51";
global.__objectNames[51] = "obj_tile_52";
global.__objectNames[52] = "obj_tile_53";
global.__objectNames[53] = "object176";
global.__objectNames[54] = "object177";
global.__objectNames[55] = "object179";
global.__objectNames[56] = "object178";
global.__objectNames[57] = "object180";
global.__objectNames[58] = "object181";
global.__objectNames[59] = "object182";
global.__objectNames[60] = "object183";
global.__objectNames[61] = "object184";
global.__objectNames[62] = "object185";
global.__objectNames[63] = "object186";
global.__objectNames[64] = "object187";
global.__objectNames[65] = "object188";
global.__objectNames[66] = "object189";
global.__objectNames[67] = "object190";
global.__objectNames[68] = "object195";
global.__objectNames[69] = "object193";
global.__objectNames[70] = "object198";
global.__objectNames[71] = "object199";
global.__objectNames[72] = "object200";
global.__objectNames[73] = "object201";
global.__objectNames[74] = "object202";
global.__objectNames[75] = "object209";
global.__objectNames[76] = "object239";
global.__objectNames[77] = "object240";
global.__objectNames[78] = "object204";
global.__objectNames[79] = "object207";
global.__objectNames[80] = "object205";
global.__objectNames[81] = "object208";
global.__objectNames[82] = "object206";
global.__objectNames[83] = "object203";
global.__objectNames[84] = "object265";
global.__objectNames[85] = "object191";
global.__objectNames[86] = "object192";
global.__objectNames[87] = "object194";
global.__objectNames[88] = "object196";
global.__objectNames[89] = "object197";
global.__objectNames[90] = "object210";
global.__objectNames[91] = "object211";
global.__objectNames[92] = "object212";
global.__objectNames[93] = "object213";
global.__objectNames[94] = "object214";
global.__objectNames[95] = "object215";
global.__objectNames[96] = "object216";
global.__objectNames[97] = "object217";
global.__objectNames[98] = "object218";
global.__objectNames[99] = "object219";
global.__objectNames[100] = "object220";
global.__objectNames[101] = "object221";
global.__objectNames[102] = "object222";
global.__objectNames[103] = "object223";
global.__objectNames[104] = "object224";
global.__objectNames[105] = "object225";
global.__objectNames[106] = "object226";
global.__objectNames[107] = "object227";
global.__objectNames[108] = "object228";
global.__objectNames[109] = "object229";
global.__objectNames[110] = "object230";
global.__objectNames[111] = "object231";
global.__objectNames[112] = "object232";
global.__objectNames[113] = "object233";
global.__objectNames[114] = "object234";
global.__objectNames[115] = "object235";
global.__objectNames[116] = "object236";
global.__objectNames[117] = "object237";
global.__objectNames[118] = "object238";
global.__objectNames[119] = "object241";
global.__objectNames[120] = "object242";
global.__objectNames[121] = "object243";
global.__objectNames[122] = "object244";
global.__objectNames[123] = "object245";
global.__objectNames[124] = "object246";
global.__objectNames[125] = "object247";
global.__objectNames[126] = "object248";
global.__objectNames[127] = "object249";
global.__objectNames[128] = "object250";
global.__objectNames[129] = "object251";
global.__objectNames[130] = "object252";
global.__objectNames[131] = "object256";
global.__objectNames[132] = "object257";
global.__objectNames[133] = "object258";
global.__objectNames[134] = "object259";
global.__objectNames[135] = "object260";
global.__objectNames[136] = "object261";
global.__objectNames[137] = "object262";
global.__objectNames[138] = "object263";
global.__objectNames[139] = "object264";
global.__objectNames[140] = "object273";
global.__objectNames[141] = "object266";
global.__objectNames[142] = "object274";
global.__objectNames[143] = "object253";
global.__objectNames[144] = "object254";
global.__objectNames[145] = "object255";
global.__objectNames[146] = "obj_player";
global.__objectNames[147] = "obj_flag";
global.__objectNames[148] = "obj_ladder";
global.__objectNames[149] = "obj_gun";
global.__objectNames[150] = "obj_jetpack";
global.__objectNames[151] = "obj_no_entry";
global.__objectNames[152] = "obj_room_next";
global.__objectNames[153] = "obj_block2";
global.__objectNames[154] = "obj_block3";
global.__objectNames[155] = "obj_win_plat";
global.__objectNames[156] = "obj_platform_h";
global.__objectNames[157] = "obj_platform_v";
global.__objectNames[158] = "obj_crumble_block";
global.__objectNames[159] = "obj_gemblock";
global.__objectNames[160] = "obj_breakable";
global.__objectNames[161] = "obj_solid";
global.__objectNames[162] = "obj_springblock";
global.__objectNames[163] = "obj_spike_d";
global.__objectNames[164] = "obj_spike_r";
global.__objectNames[165] = "obj_spike";
global.__objectNames[166] = "obj_spike_l";
global.__objectNames[167] = "obj_water";
global.__objectNames[168] = "obj_example_enemy";
global.__objectNames[169] = "obj_spike_u";
global.__objectNames[170] = "obj_stationary";
global.__objectNames[171] = "obj_walker";
global.__objectNames[172] = "obj_riser";
global.__objectNames[173] = "obj_ducker";
global.__objectNames[174] = "obj_faller";
global.__objectNames[175] = "obj_jumper";
global.__objectNames[176] = "obj_floater";
global.__objectNames[177] = "obj_sticky";
global.__objectNames[178] = "obj_waver";
global.__objectNames[179] = "obj_swinger";
global.__objectNames[180] = "obj_follower";
global.__objectNames[181] = "obj_liner";
global.__objectNames[182] = "obj_ponger";
global.__objectNames[183] = "obj_geobound";
global.__objectNames[184] = "obj_tethered";
global.__objectNames[185] = "obj_swooper";
global.__objectNames[186] = "par_enemy";
global.__objectNames[187] = "par_platform";
global.__objectNames[188] = "par_event";
global.__objectNames[189] = "par_solid";
global.__objectNames[190] = "par_ladder";
global.__objectNames[191] = "par_liquid";
global.__objectNames[192] = "obj_commands";
global.__objectNames[193] = "obj_gen";
global.__objectNames[194] = "obj_data";
global.__objectNames[195] = "obj_gui";
global.__objectNames[196] = "obj_music";
global.__objectNames[197] = "obj_view";
global.__objectNames[198] = "obj_instance_control";
global.__objectNames[199] = "obj_camera";
global.__objectNames[200] = "obj_room";
global.__objectNames[201] = "obj_game_over";
global.__objectNames[202] = "obj_disappear";
global.__objectNames[203] = "obj_go_to_boss";
global.__objectNames[204] = "obj_trans_waterfall1";
global.__objectNames[205] = "obj_trans_waterfall2";
global.__objectNames[206] = "obj_transition_open";
global.__objectNames[207] = "obj_transition_close";
global.__objectNames[208] = "obj_waterfall";
global.__objectNames[209] = "obj_levelportal";
global.__objectNames[210] = "obj_levelportal_2";
global.__objectNames[211] = "obj_pedestal";
global.__objectNames[212] = "obj_item";
global.__objectNames[213] = "obj_title";
global.__objectNames[214] = "obj_particle_jump";
global.__objectNames[215] = "obj_particle_land";
global.__objectNames[216] = "obj_drillsparks";
global.__objectNames[217] = "obj_enemy_shot";
global.__objectNames[218] = "obj_cannonball";
global.__objectNames[219] = "obj_run_timer";
global.__objectNames[220] = "obj_win_timer";
global.__objectNames[221] = "obj_blacksolid";
global.__objectNames[222] = "obj_invisblock";
global.__objectNames[223] = "obj_water2";
global.__objectNames[224] = "obj_chunk";
global.__objectNames[225] = "obj_chunk_breakable";
global.__objectNames[226] = "obj_chunk_solid";
global.__objectNames[227] = "obj_chunk_surface";
global.__objectNames[228] = "obj_block_spawner";
global.__objectNames[229] = "obj_blood_splat";
global.__objectNames[230] = "obj_burst_particle";
global.__objectNames[231] = "obj_explosion";
global.__objectNames[232] = "obj_explosion_2";
global.__objectNames[233] = "obj_explosion_silent";
global.__objectNames[234] = "obj_ore";
global.__objectNames[235] = "obj_next_room";
global.__objectNames[236] = "obj_piece";
global.__objectNames[237] = "obj_platform";
global.__objectNames[238] = "obj_platform_backup";
global.__objectNames[239] = "obj_shot";
global.__objectNames[240] = "obj_shot_splash";
global.__objectNames[241] = "obj_shot_splash_invul";
global.__objectNames[242] = "obj_shot_splash_dir";
global.__objectNames[243] = "obj_train";
global.__objectNames[244] = "obj_train_door";
global.__objectNames[245] = "obj_train_platform";
global.__objectNames[246] = "obj_switch_call";
global.__objectNames[247] = "obj_switch_dismiss";
global.__objectNames[248] = "obj_train_interior";
global.__objectNames[249] = "obj_train_floor";
global.__objectNames[250] = "obj_train_ceiling";
global.__objectNames[251] = "obj_conductor";
global.__objectNames[252] = "obj_speech";
global.__objectNames[253] = "obj_furnace";
global.__objectNames[254] = "obj_create_player";
global.__objectNames[255] = "obj_lilboy";
global.__objectNames[256] = "obj_boss_plat";
global.__objectNames[257] = "obj_crawler";
global.__objectNames[258] = "obj_pipe";
global.__objectNames[259] = "spr_blobboy";
global.__objectNames[260] = "obj_longboy";
global.__objectNames[261] = "obj_lickboy";
global.__objectNames[262] = "obj_boulder";
global.__objectNames[263] = "obj_enemy";
global.__objectNames[264] = "obj_floaty";
global.__objectNames[265] = "obj_boss";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for